package modelo;
// Generated 16-feb-2011 10:22:20 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nif;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String tipo;
     private String departamento;
     private Set notificacionesesForDestinatario = new HashSet(0);
     private Set notificacionesesForRemitente = new HashSet(0);
     private Set autentificacions = new HashSet(0);
     private Set cuadriculas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nif, String nombre, String apellido1, String tipo) {
        this.nif = nif;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.tipo = tipo;
    }
    public Usuario(String nif, String nombre, String apellido1, String apellido2, String tipo, String departamento, Set notificacionesesForDestinatario, Set notificacionesesForRemitente, Set autentificacions, Set cuadriculas) {
       this.nif = nif;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.tipo = tipo;
       this.departamento = departamento;
       this.notificacionesesForDestinatario = notificacionesesForDestinatario;
       this.notificacionesesForRemitente = notificacionesesForRemitente;
       this.autentificacions = autentificacions;
       this.cuadriculas = cuadriculas;
    }
   
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getNotificacionesesForDestinatario() {
        return this.notificacionesesForDestinatario;
    }
    
    public void setNotificacionesesForDestinatario(Set notificacionesesForDestinatario) {
        this.notificacionesesForDestinatario = notificacionesesForDestinatario;
    }
    public Set getNotificacionesesForRemitente() {
        return this.notificacionesesForRemitente;
    }
    
    public void setNotificacionesesForRemitente(Set notificacionesesForRemitente) {
        this.notificacionesesForRemitente = notificacionesesForRemitente;
    }
    public Set getAutentificacions() {
        return this.autentificacions;
    }
    
    public void setAutentificacions(Set autentificacions) {
        this.autentificacions = autentificacions;
    }
    public Set getCuadriculas() {
        return this.cuadriculas;
    }
    
    public void setCuadriculas(Set cuadriculas) {
        this.cuadriculas = cuadriculas;
    }




}


