package modelo.notificaciones;
// Generated 16-feb-2011 10:22:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * NotificacionPendiente generated by hbm2java
 */
public class NotificacionPendiente extends Notificaciones implements java.io.Serializable {

     private Date plazo;

    public NotificacionPendiente() {
    }

    public Date getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Date plazo) {
        this.plazo = plazo;
    }




}


